version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:stable
        environment:
          SHELLCHECK_OPTS: "-e SC2086 -e SC2162 -e SC3043 -e SC2236 -e SC3024 -e SC2181 -e SC2046 -e SC2155 -e SC2126 -e SC2034"
    steps:
     - checkout
     - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources